/** Curated lists formerly in `scan_engine.analyzers.traffic` (Python). */

export const HIGH_RISK_ENDPOINTS: readonly string[] = [
  "/wp-login.php",
  "/wp-admin",
  "/admin",
  "/administrator",
  "/phpmyadmin",
  "/pma",
  "/myadmin",
  "/mysql",
  "/xmlrpc.php",
  "/wp-config.php",
  "/.env",
  "/.git",
  "/.git/config",
  "/.htaccess",
  "/.htpasswd",
  "/config.php",
  "/backup",
  "/shell",
  "/cmd",
  "/eval",
  "/exec",
  "/cgi-bin",
  "/scripts",
  "/.aws",
  "/.ssh",
  "/id_rsa",
  "/passwd",
  "/shadow",
  "/etc/passwd",
  "/proc/self",
  "/api/v1/pods",
  "/actuator",
  "/console",
  "/manager/html",
  "/solr/admin",
] as const;

export const MALICIOUS_BOT_SIGNATURES: readonly string[] = [
  "sqlmap",
  "nikto",
  "nessus",
  "nmap",
  "masscan",
  "zgrab",
  "gobuster",
  "dirbuster",
  "wfuzz",
  "ffuf",
  "hydra",
  "burp",
  "acunetix",
  "netsparker",
  "appscan",
  "w3af",
  "havij",
  "python-requests",
  "go-http-client",
  "curl/",
  "wget/",
  "libwww-perl",
  "scanbot",
  "crawler",
  "spider",
  "ahrefsbot",
  "semrushbot",
  "dotbot",
  "mj12bot",
  "screaming frog",
  "heritrix",
  "censys",
  "shodan",
] as const;
