# Generated by Django 6.0.3 on 2026-03-23 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public-facing identifier used to look up this scan result.', unique=True)),
                ('url', models.URLField(help_text='The URL that was scanned.', max_length=2048)),
                ('score', models.IntegerField(help_text='Threat score from 0 (safe) to 100 (critical).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('results', models.JSONField(help_text='Full scan result payload returned by the Flask engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this report is considered expired.')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.scan')),
            ],
            options={
                'ordering': ['-scan__created_at'],
            },
        ),
    ]
