# Generated by Django 6.0.3 on 2026-03-28 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_target_scan_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='score',
            field=models.IntegerField(help_text='Composite posture score 0–100 from the scan engine (higher is better).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
