# Generated by Django 6.0.3 on 2026-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_user_cloudflare_credentials'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['target', '-created_at'], name='scan_target_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['url', '-created_at'], name='scan_url_created_idx'),
        ),
    ]
